CFLAGS=-Wall -Wextra -Isrc -O0 -DPC -fmerge-all-constants -fsingle-precision-constant -ggdb -fdata-sections -ffunction-sections -Wl,--gc-sections -pipe
objects = src/main.o src/screen.o src/input.o src/mandelbrot.o

mandelbort: $(objects)
	cc -Wall -o mandelbrot -lSDL -lm $(CFLAGS) $(objects)

%.o: %.cpp
	cc $(CFLAGS) -c $< -o $@
%.o: %.c
	cc $(CFLAGS) -c $< -o $@
clean:
	rm -f mandelbrot $(objects)
